### ISSUE TITLE
Feature: The chart needs values.yaml option to add init containers and extra volumes

### ISSUE THREAD

**Issue by zerthimon** [manticoresoftware/manticoresearch-helm#4]
This is needed if the one wants to have a lemmatizer dictionaries and wordforms.

in configmap:
```
      common
      {
        lemmatizer_base = /usr/local/share/manticore/dicts
      }
```

```
      initContainers:
      - name: {{ .Chart.Name }}-words
        securityContext:
          runAsUser: 0
        image: "{{ .Values.words.image.registry }}/{{ .Values.words.image.repository }}:{{ .Values.words.image.tag }}"
        imagePullPolicy: IfNotPresent
        command: ['/bin/sh']
        args:
        - '-c'
        - |
          mkdir /words/words /words/dicts
          cp {{ .Values.words.path }}/* /words/words
          wget -O /words/dicts/ru.pak http://docs.manticoresearch.com/dict/ru.pak
          wget -O /words/dicts/en.pak http://docs.manticoresearch.com/dict/en.pak
        volumeMounts:
        - name: words
          mountPath: /words
```
for worker container:
```
          - name: words
            mountPath: /usr/local/share/manticore
```
for pod:
```
        - name: words
          emptyDir: {}
```

Check out Bitnami helm charts for how to add extra init containers and extra volumes.
