### ISSUE TITLE
Some bugs then deploy helm on k8's

### ISSUE THREAD

**Issue by akametall** [manticoresoftware/manticoresearch-helm#78]
Then i deploy this on k8's

> config:
>
>path: /mnt/manticore.conf
>content: |
>searchd {
>listen = /var/run/mysqld/mysqld.sock:mysql41
>listen = 9306:mysql41
>listen = 9308:http
>listen = $hostname:9312
>listen = $hostname:9315-9415:replication
>node_address = $hostname
>binlog_path = /var/lib/manticore
>pid_file = /var/run/manticore/searchd.pid
>shutdown_timeout = 25s
>auto_optimize = 0
>}
>source *** {
>type = pgsql
>sql_host = ***
>sql_user = postgres
>sql_pass = $PASSWORD
>sql_db = ***
>}
>index ***_index {
>type = plain
>source = ***
>path = ***
>}

 i get this in logs    

>precaching table '***_index'
>Index header format is not json, will try it as binary...
>WARNING: Unable to load header... Error failed to open i.sph: No such file or directory
>WARNING: table '_index': prealloc: failed to open ***.sph: No such file or directory - NOT SERVING

and this

>2023-11-14 16:37:39,358 INFO success: searchd entered RUNNING state, process has stayed up for > than 1 seconds >(startsecs)
>[2023-11-14T16:37:39.745240+00:00] Logs.INFO: Wait until manticoresearch-worker-1 came alive [] []
>[2023-11-14T16:37:41.767922+00:00] Logs.INFO: Wait for NS... [] []
>[2023-11-14T16:37:53.659698+00:00] Logs.INFO: Wait until join host come available ["manticoresearch-worker->0.manticoresearch-worker-svc",9306] []PHP Warning: mysqli::__construct(): php_network_getaddresses: getaddrinfo for >manticoresearch-worker-0.manticoresearch-worker-svc failed: Name or service not known in >/etc/manticoresearch/vendor/manticoresoftware/manticoresearch-auto-replication/src/Manticore/ManticoreConnector.php on >line 35

my yml

```
global:
  manticoresearch: {}

balancer:
  replicaCount: 1
  runInterval: 5
  extraPackages: false
  image:
    repository: manticoresearch/helm-balancer
    pullPolicy: IfNotPresent
  config:
    path: /mnt/configmap.conf
    index_ha_strategy: nodeads
    content: |
      searchd
      {
        listen = /var/run/mysqld/mysqld.sock:mysql
        listen = 9306:mysql
        listen = 9308:http
        log = /dev/stdout
        query_log = /dev/stdout
        pid_file = /var/run/manticore/searchd.pid
        binlog_path = /var/lib/manticore
        shutdown_timeout = 25s
        auto_optimize = 0
      }
  service:
    ql:
      port: 9306
      targetPort: 9306
    observer:
      port: 8080
      targetPort: 8080
    http:
      port: 9308
      targetPort: 9308
    binary:
      port: 9312
      targetPort: 9312
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

worker:
  replicaCount: 2
  clusterName: manticore
  config:
    path: /mnt/manticore.conf
    content: |
      searchd {
        listen = /var/run/mysqld/mysqld.sock:mysql41
        listen = 9306:mysql41
        listen = 9308:http
        listen = $hostname:9312
        listen = $hostname:9315-9415:replication
        node_address = $hostname
        binlog_path = /var/lib/manticore
        pid_file = /var/run/manticore/searchd.pid
        shutdown_timeout = 25s
        auto_optimize = 0
      }
      source * {
        type = pgsql
        sql_host = *
        sql_user = postgres
        sql_pass = $*PASSWORD
        sql_db = *
      }
      index *_index {
        type = plain
        source = *
        path = *
      }
  replicationMode: master-slave
  quorumRecovery: false
  extraPackages: false
  quorumCheckInterval: 15
  autoAddTablesInCluster: false
  logLevel: INFO
  image:
    repository: manticoresearch/helm-worker
    pullPolicy: IfNotPresent
  service:
    ql:
      port: 9306
      targetPort: 9306
    http:
      port: 9308
      targetPort: 9308
    binary:
      port: 9312
      targetPort: 9312
  persistence:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 1Gi
    matchLabels: {}
    matchExpressions: {}
  volume:
    size: 1Gi
    storageClassName: false
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

exporter:
  enabled: false
  image:
    repository: manticoresearch/prometheus-exporter
    pullPolicy: IfNotPresent
    tag: 5.0.2.5
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "8081"
    prometheus.io/scrape: "true"
  resources: {}


serviceMonitor:
  enabled: true
  interval: 30s
  scrapeTimeout: 10s
optimize:
  enabled: true
  interval: "30"
  coefficient: "2"
imagePullSecrets: []
nameOverride: ""
fullNameOverride: manticoresearch
serviceAccount:
  annotations: {}
  name: "manticore-sa"
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
nodeSelector: {}
tolerations: []
affinity: {}
persistence: {}
```
